### ISSUE TITLE
Please release binary file

### ISSUE THREAD

**Issue by Llesue** [andrewhodel/dotblog#1]

**Comment by andrewhodel** [comment]
You can install Go.

The instructions are available at this link - https://go.dev/doc/install

Once Go is installed, you can follow the instructions at this link to use Dotblog - https://github.com/andrewhodel/dotblog/blob/main/README.md

**Comment by Llesue** [comment]
> You can install Go.
> 
> The instructions are available at this link - https://go.dev/doc/install
> 
> Once Go is installed, you can follow the instructions at this link to use Dotblog - https://github.com/andrewhodel/dotblog/blob/main/README.md

```
root@RouterDebian:~/go/dotblog(main○) # GO111MODULE=off go get -u github.com/andrewhodel/go-ip-ac  1 ↵
root@RouterDebian:~/go/dotblog(main○) # go run dotblog_server.go                                 
dotblog_server.go:29:2: no required module provides package github.com/andrewhodel/go-ip-ac: go.mod file not found in current directory or any parent directory; see 'go help modules'
```
I really like to use this blog engine with my own designed html... But there's too many errors with it. And i'm new to golang. So i can't run it.

**Comment by andrewhodel** [comment]
Read the instructions.

https://github.com/andrewhodel/dotblog/blob/main/README.md

**This is the section that you did not read.**

<img width="972" alt="Screenshot 2023-06-04 at 8 51 14 PM" src="https://github.com/andrewhodel/dotblog/assets/741705/5bdeaa06-7bd8-47ed-b077-2f5ffecb6df0">

The command you executed to run the server does not include 2 environment variables.
